image: maven:3.3.9-jdk-8

stages:
  - compile
  - test
  - build
  - deploy
  - other

update_docker:
  stage: other
  image: docker:stable
  script:
      - docker -H=10.10.1.6:2376 rmi $(docker -H=10.10.1.6:2376 | grep "^<none>")
