image: maven:3.3.9-jdk-8

stages:
  - compile
  - test
  - build
  - deploy

maven_install:
  stage: build
  script:
    - mvn install -DskipTests
    - ls
  artifacts:
      expire_in: 1 hrs
      paths:
      - restservice/target/restservice.jar
  only:
    refs:
      - master

deploy_rest:
  stage: deploy
  script:
    - cd restservice/
    - mvn install -Ddocker.host=http://10.10.1.6:2376
  when: on_success
  only:
    refs:
      - master
