image: maven:3.3.9-jdk-8

variables:
  IP_REST: "10.10.1.5"

before_script:
  - mkdir ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
  - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts

stages:
  - compile
  - test
  - build
  - deploy

maven_compile:
  stage: compile
  script:
    - mvn compile

maven_test:
  stage: test
  script:
    - mvn test
  when: on_success

maven_install:
  stage: build
  script:
    - mvn install -DskipTests
  when: on_success
  artifacts:
      expire_in: 1 hrs
      paths:
      - restservice/target/restservice.jar
  only:
    refs:
      - master

deploy_rest:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - cd restservice/
    - mvn install -Ddocker.host=http://10.10.1.6:2376
  when: on_success
  only:
    refs:
      - master
