image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "10.10.1.6"

stages:
  - compile
  - test
  - package
  - deploy

compiling:
  stage: compile
  script:
    - mvn compile

testing:
  stage: test
  script:
    - mvn test
  when: on_success

packaging:
  stage: package
  script:
    - mvn package -DskipTests
  when: on_success

deploy_image:
  stage: deploy
  script:
    - mvn install -pl web-service,rest-service -am
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts
    - cd ../
    - ssh jobswitch@$IP_DOCKER "rm -r public-html/"
    - scp -r api/ jobswitch@$IP_DOCKER:public-html/
    - ssh jobswitch@$IP_DOCKER "sudo ./startMylabClean.sh"
  when: on_success
  only:
    refs:
      - master