image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "10.10.1.6"

stages:
  - compile
  - test
  - build
  - deploy
  - other

update_docker:
  stage: other
  script:
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts
    - ssh jobswitch@$IP_DOCKER "sudo /home/jobswitch/./startMylabClean.sh"
