image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "10.10.1.6"

stages:
  - compile
  - test
  - package
  - deploy

compiling:
  stage: compile
  script:
    - mvn compile

testing:
  stage: test
  script:
    - mvn test
  when: on_success

packaging:
  stage: package
  script:
    - mvn package -DskipTests
  when: on_success

packageAndroid:
  stage: package
  image: marcolizza/docker-android-sdk:latest
  script:
    - cd jobswitch-android/
    - chmod +x ./gradlew
    - ./gradlew assemble
    - cd ..
  artifacts:
      expire_in: 2 hrs
      paths:
      - jobswitch-android/app/build/outputs/apk/app-debug.apk
  when: on_success

deploy_apk:
  stage: deploy
  dependencies:
    - packageAndroid
  script:
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts
    - scp jobswitch-android/app/build/outputs/apk/app-debug.apk jobswitch@$IP_DOCKER:/var/www/html/app.apk
  when: on_success
  only:
    refs:
      - master

deploy_image:
  stage: deploy
  script:
    - mvn install -pl webservice,restservice -am
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts
    - ssh jobswitch@$IP_DOCKER "rm -r public-html/"
    - scp -r api/ jobswitch@$IP_DOCKER:public-html/
    - ssh jobswitch@$IP_DOCKER "sudo ./startMylabClean.sh"
  when: on_success
  only:
    refs:
      - master