image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "10.10.1.6"

stages:
  - compile
  - test
  - build
  - deploy
  - other

maven_compile:
  stage: compile
  script:
    - mvn compile

maven_test:
  stage: test
  script:
    - mvn test
  when: on_success

maven_install:
  stage: build
  script:
    - mvn package -DskipTests
  only:
    refs:
      - master

deploy_rest:
  stage: deploy
  script:
    - cd restservice/
    - mvn install -Ddocker.host=http://10.10.1.6:2376
  when: on_success
  only:
    refs:
      - master

update_docker:
  stage: other
  script:
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts
    - ssh esibank@$IP_DOCKER "sudo /home/jobswitch/./startMylabClean.sh"
