swagger: '2.0'
info:
  description: Description d'utilisation de l'API de l'application REST de JobSwitch.
  version: 1.0.0
  title: API JobSwitch
  contact:
    name: BOURGEOIS Thibault & EDERY Ruben
    email: thibault.bourgeois@etu.u-pec.fr
host: 'rest.jobswitch.inside.esiag.info'
basePath: /
tags:
  - name: sample
    description: operation sample
schemes:
  - http
paths:
  '/sample':
    get:
      tags:
        - sample
      summary: Get all sample
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Sample'
definitions:
  Sample:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      myString:
        type: string
        example: test